name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  # schedule:
  #   - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'laravel'
          mysql user: root
          mysql password: password

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: |
          cp .env.example .env
          echo DB_PASSWORD=password >> .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Build frontend assets
        run: npm install --legacy-peer-deps
          npm run build

      - name: Execute tests
        run: vendor/bin/phpunit
